/*
 * RAWG Video Games Database API
 *  The largest open video games database.  ### Why build on RAWG - More than 350,000 games for 50 platforms including mobiles. - Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates, Metacritic ratings. - Where to buy: links to digital distribution services - Similar games based on visual similarity. - Player activity data: Steam average playtime and RAWG player counts and ratings. - Actively developing and constantly getting better by user contribution and our algorithms.  ### Terms of Use - Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active hyperlink from every page where the data of RAWG is used. - Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000 page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for commercial terms. - No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt, and we will talk it through. - You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs. If you don’t provide it, we may ban your requests.  __[Read more](https://rawg.io/apidocs)__. 
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.net.URI;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GameEsrbRating;
import org.openapitools.client.model.GamePlatformsInner;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Game
 */
@JsonPropertyOrder({
  Game.JSON_PROPERTY_ID,
  Game.JSON_PROPERTY_SLUG,
  Game.JSON_PROPERTY_NAME,
  Game.JSON_PROPERTY_RELEASED,
  Game.JSON_PROPERTY_TBA,
  Game.JSON_PROPERTY_BACKGROUND_IMAGE,
  Game.JSON_PROPERTY_RATING,
  Game.JSON_PROPERTY_RATING_TOP,
  Game.JSON_PROPERTY_RATINGS,
  Game.JSON_PROPERTY_RATINGS_COUNT,
  Game.JSON_PROPERTY_REVIEWS_TEXT_COUNT,
  Game.JSON_PROPERTY_ADDED,
  Game.JSON_PROPERTY_ADDED_BY_STATUS,
  Game.JSON_PROPERTY_METACRITIC,
  Game.JSON_PROPERTY_PLAYTIME,
  Game.JSON_PROPERTY_SUGGESTIONS_COUNT,
  Game.JSON_PROPERTY_UPDATED,
  Game.JSON_PROPERTY_ESRB_RATING,
  Game.JSON_PROPERTY_PLATFORMS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T10:31:14.408Z[UTC]")
public class Game {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_SLUG = "slug";
  private String slug;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_RELEASED = "released";
  private LocalDate released;

  public static final String JSON_PROPERTY_TBA = "tba";
  private Boolean tba;

  public static final String JSON_PROPERTY_BACKGROUND_IMAGE = "background_image";
  private URI backgroundImage;

  public static final String JSON_PROPERTY_RATING = "rating";
  private BigDecimal rating;

  public static final String JSON_PROPERTY_RATING_TOP = "rating_top";
  private Integer ratingTop;

  public static final String JSON_PROPERTY_RATINGS = "ratings";
  private Object ratings;

  public static final String JSON_PROPERTY_RATINGS_COUNT = "ratings_count";
  private Integer ratingsCount;

  public static final String JSON_PROPERTY_REVIEWS_TEXT_COUNT = "reviews_text_count";
  private String reviewsTextCount;

  public static final String JSON_PROPERTY_ADDED = "added";
  private Integer added;

  public static final String JSON_PROPERTY_ADDED_BY_STATUS = "added_by_status";
  private Object addedByStatus;

  public static final String JSON_PROPERTY_METACRITIC = "metacritic";
  private Integer metacritic;

  public static final String JSON_PROPERTY_PLAYTIME = "playtime";
  private Integer playtime;

  public static final String JSON_PROPERTY_SUGGESTIONS_COUNT = "suggestions_count";
  private Integer suggestionsCount;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  private OffsetDateTime updated;

  public static final String JSON_PROPERTY_ESRB_RATING = "esrb_rating";
  private JsonNullable<GameEsrbRating> esrbRating = JsonNullable.<GameEsrbRating>undefined();

  public static final String JSON_PROPERTY_PLATFORMS = "platforms";
  private List<GamePlatformsInner> platforms = null;

  public Game() {
  }

  @JsonCreator
  public Game(
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_SLUG) String slug, 
    @JsonProperty(JSON_PROPERTY_NAME) String name, 
    @JsonProperty(JSON_PROPERTY_RELEASED) LocalDate released, 
    @JsonProperty(JSON_PROPERTY_TBA) Boolean tba, 
    @JsonProperty(JSON_PROPERTY_BACKGROUND_IMAGE) URI backgroundImage, 
    @JsonProperty(JSON_PROPERTY_RATING_TOP) Integer ratingTop, 
    @JsonProperty(JSON_PROPERTY_RATINGS) Object ratings, 
    @JsonProperty(JSON_PROPERTY_RATINGS_COUNT) Integer ratingsCount, 
    @JsonProperty(JSON_PROPERTY_REVIEWS_TEXT_COUNT) String reviewsTextCount, 
    @JsonProperty(JSON_PROPERTY_ADDED) Integer added, 
    @JsonProperty(JSON_PROPERTY_ADDED_BY_STATUS) Object addedByStatus, 
    @JsonProperty(JSON_PROPERTY_METACRITIC) Integer metacritic, 
    @JsonProperty(JSON_PROPERTY_PLAYTIME) Integer playtime, 
    @JsonProperty(JSON_PROPERTY_SUGGESTIONS_COUNT) Integer suggestionsCount, 
    @JsonProperty(JSON_PROPERTY_UPDATED) OffsetDateTime updated
  ) {
    this();
    this.id = id;
    this.slug = slug;
    this.name = name;
    this.released = released;
    this.tba = tba;
    this.backgroundImage = backgroundImage;
    this.ratingTop = ratingTop;
    this.ratings = ratings;
    this.ratingsCount = ratingsCount;
    this.reviewsTextCount = reviewsTextCount;
    this.added = added;
    this.addedByStatus = addedByStatus;
    this.metacritic = metacritic;
    this.playtime = playtime;
    this.suggestionsCount = suggestionsCount;
    this.updated = updated;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }




   /**
   * Get slug
   * @return slug
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SLUG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSlug() {
    return slug;
  }




   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }




   /**
   * Get released
   * @return released
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELEASED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getReleased() {
    return released;
  }




   /**
   * Get tba
   * @return tba
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TBA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTba() {
    return tba;
  }




   /**
   * Get backgroundImage
   * @return backgroundImage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BACKGROUND_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getBackgroundImage() {
    return backgroundImage;
  }




  public Game rating(BigDecimal rating) {
    
    this.rating = rating;
    return this;
  }

   /**
   * Get rating
   * @return rating
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_RATING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getRating() {
    return rating;
  }


  @JsonProperty(JSON_PROPERTY_RATING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRating(BigDecimal rating) {
    this.rating = rating;
  }


   /**
   * Get ratingTop
   * @return ratingTop
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RATING_TOP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRatingTop() {
    return ratingTop;
  }




   /**
   * Get ratings
   * @return ratings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RATINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getRatings() {
    return ratings;
  }




   /**
   * Get ratingsCount
   * @return ratingsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RATINGS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRatingsCount() {
    return ratingsCount;
  }




   /**
   * Get reviewsTextCount
   * @return reviewsTextCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REVIEWS_TEXT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReviewsTextCount() {
    return reviewsTextCount;
  }




   /**
   * Get added
   * @return added
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAdded() {
    return added;
  }




   /**
   * Get addedByStatus
   * @return addedByStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDED_BY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAddedByStatus() {
    return addedByStatus;
  }




   /**
   * Get metacritic
   * @return metacritic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METACRITIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMetacritic() {
    return metacritic;
  }




   /**
   * in hours
   * @return playtime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "in hours")
  @JsonProperty(JSON_PROPERTY_PLAYTIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPlaytime() {
    return playtime;
  }




   /**
   * Get suggestionsCount
   * @return suggestionsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUGGESTIONS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSuggestionsCount() {
    return suggestionsCount;
  }




   /**
   * Get updated
   * @return updated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdated() {
    return updated;
  }




  public Game esrbRating(GameEsrbRating esrbRating) {
    this.esrbRating = JsonNullable.<GameEsrbRating>of(esrbRating);
    
    return this;
  }

   /**
   * Get esrbRating
   * @return esrbRating
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public GameEsrbRating getEsrbRating() {
        return esrbRating.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ESRB_RATING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<GameEsrbRating> getEsrbRating_JsonNullable() {
    return esrbRating;
  }
  
  @JsonProperty(JSON_PROPERTY_ESRB_RATING)
  public void setEsrbRating_JsonNullable(JsonNullable<GameEsrbRating> esrbRating) {
    this.esrbRating = esrbRating;
  }

  public void setEsrbRating(GameEsrbRating esrbRating) {
    this.esrbRating = JsonNullable.<GameEsrbRating>of(esrbRating);
  }


  public Game platforms(List<GamePlatformsInner> platforms) {
    
    this.platforms = platforms;
    return this;
  }

  public Game addPlatformsItem(GamePlatformsInner platformsItem) {
    if (this.platforms == null) {
      this.platforms = new ArrayList<>();
    }
    this.platforms.add(platformsItem);
    return this;
  }

   /**
   * Get platforms
   * @return platforms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PLATFORMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GamePlatformsInner> getPlatforms() {
    return platforms;
  }


  @JsonProperty(JSON_PROPERTY_PLATFORMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatforms(List<GamePlatformsInner> platforms) {
    this.platforms = platforms;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Game game = (Game) o;
    return Objects.equals(this.id, game.id) &&
        Objects.equals(this.slug, game.slug) &&
        Objects.equals(this.name, game.name) &&
        Objects.equals(this.released, game.released) &&
        Objects.equals(this.tba, game.tba) &&
        Objects.equals(this.backgroundImage, game.backgroundImage) &&
        Objects.equals(this.rating, game.rating) &&
        Objects.equals(this.ratingTop, game.ratingTop) &&
        Objects.equals(this.ratings, game.ratings) &&
        Objects.equals(this.ratingsCount, game.ratingsCount) &&
        Objects.equals(this.reviewsTextCount, game.reviewsTextCount) &&
        Objects.equals(this.added, game.added) &&
        Objects.equals(this.addedByStatus, game.addedByStatus) &&
        Objects.equals(this.metacritic, game.metacritic) &&
        Objects.equals(this.playtime, game.playtime) &&
        Objects.equals(this.suggestionsCount, game.suggestionsCount) &&
        Objects.equals(this.updated, game.updated) &&
        equalsNullable(this.esrbRating, game.esrbRating) &&
        Objects.equals(this.platforms, game.platforms);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, slug, name, released, tba, backgroundImage, rating, ratingTop, ratings, ratingsCount, reviewsTextCount, added, addedByStatus, metacritic, playtime, suggestionsCount, updated, hashCodeNullable(esrbRating), platforms);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Game {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    released: ").append(toIndentedString(released)).append("\n");
    sb.append("    tba: ").append(toIndentedString(tba)).append("\n");
    sb.append("    backgroundImage: ").append(toIndentedString(backgroundImage)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    ratingTop: ").append(toIndentedString(ratingTop)).append("\n");
    sb.append("    ratings: ").append(toIndentedString(ratings)).append("\n");
    sb.append("    ratingsCount: ").append(toIndentedString(ratingsCount)).append("\n");
    sb.append("    reviewsTextCount: ").append(toIndentedString(reviewsTextCount)).append("\n");
    sb.append("    added: ").append(toIndentedString(added)).append("\n");
    sb.append("    addedByStatus: ").append(toIndentedString(addedByStatus)).append("\n");
    sb.append("    metacritic: ").append(toIndentedString(metacritic)).append("\n");
    sb.append("    playtime: ").append(toIndentedString(playtime)).append("\n");
    sb.append("    suggestionsCount: ").append(toIndentedString(suggestionsCount)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    esrbRating: ").append(toIndentedString(esrbRating)).append("\n");
    sb.append("    platforms: ").append(toIndentedString(platforms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

