/*
 * RAWG Video Games Database API
 *  The largest open video games database.  ### Why build on RAWG - More than 350,000 games for 50 platforms including mobiles. - Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates, Metacritic ratings. - Where to buy: links to digital distribution services - Similar games based on visual similarity. - Player activity data: Steam average playtime and RAWG player counts and ratings. - Actively developing and constantly getting better by user contribution and our algorithms.  ### Terms of Use - Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active hyperlink from every page where the data of RAWG is used. - Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000 page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for commercial terms. - No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt, and we will talk it through. - You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs. If you don’t provide it, we may ban your requests.  __[Read more](https://rawg.io/apidocs)__. 
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GamePlatformsInnerPlatform;
import org.openapitools.client.model.GamePlatformsInnerRequirements;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GamePlatformsInner
 */
@JsonPropertyOrder({
  GamePlatformsInner.JSON_PROPERTY_PLATFORM,
  GamePlatformsInner.JSON_PROPERTY_RELEASED_AT,
  GamePlatformsInner.JSON_PROPERTY_REQUIREMENTS
})
@JsonTypeName("Game_platforms_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-16T10:31:14.408Z[UTC]")
public class GamePlatformsInner {
  public static final String JSON_PROPERTY_PLATFORM = "platform";
  private GamePlatformsInnerPlatform platform;

  public static final String JSON_PROPERTY_RELEASED_AT = "released_at";
  private JsonNullable<String> releasedAt = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_REQUIREMENTS = "requirements";
  private JsonNullable<GamePlatformsInnerRequirements> requirements = JsonNullable.<GamePlatformsInnerRequirements>undefined();

  public GamePlatformsInner() {
  }

  public GamePlatformsInner platform(GamePlatformsInnerPlatform platform) {
    
    this.platform = platform;
    return this;
  }

   /**
   * Get platform
   * @return platform
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GamePlatformsInnerPlatform getPlatform() {
    return platform;
  }


  @JsonProperty(JSON_PROPERTY_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatform(GamePlatformsInnerPlatform platform) {
    this.platform = platform;
  }


  public GamePlatformsInner releasedAt(String releasedAt) {
    this.releasedAt = JsonNullable.<String>of(releasedAt);
    
    return this;
  }

   /**
   * Get releasedAt
   * @return releasedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getReleasedAt() {
        return releasedAt.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RELEASED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getReleasedAt_JsonNullable() {
    return releasedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_RELEASED_AT)
  public void setReleasedAt_JsonNullable(JsonNullable<String> releasedAt) {
    this.releasedAt = releasedAt;
  }

  public void setReleasedAt(String releasedAt) {
    this.releasedAt = JsonNullable.<String>of(releasedAt);
  }


  public GamePlatformsInner requirements(GamePlatformsInnerRequirements requirements) {
    this.requirements = JsonNullable.<GamePlatformsInnerRequirements>of(requirements);
    
    return this;
  }

   /**
   * Get requirements
   * @return requirements
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public GamePlatformsInnerRequirements getRequirements() {
        return requirements.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_REQUIREMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<GamePlatformsInnerRequirements> getRequirements_JsonNullable() {
    return requirements;
  }
  
  @JsonProperty(JSON_PROPERTY_REQUIREMENTS)
  public void setRequirements_JsonNullable(JsonNullable<GamePlatformsInnerRequirements> requirements) {
    this.requirements = requirements;
  }

  public void setRequirements(GamePlatformsInnerRequirements requirements) {
    this.requirements = JsonNullable.<GamePlatformsInnerRequirements>of(requirements);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GamePlatformsInner gamePlatformsInner = (GamePlatformsInner) o;
    return Objects.equals(this.platform, gamePlatformsInner.platform) &&
        equalsNullable(this.releasedAt, gamePlatformsInner.releasedAt) &&
        equalsNullable(this.requirements, gamePlatformsInner.requirements);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(platform, hashCodeNullable(releasedAt), hashCodeNullable(requirements));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GamePlatformsInner {\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    releasedAt: ").append(toIndentedString(releasedAt)).append("\n");
    sb.append("    requirements: ").append(toIndentedString(requirements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

